# Site
repository: ghabreu/ghabreu.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Gustavo Abreu
title: Digital Fabrication and Computer Networking Specialist
email: info@gustavoabr.eu
# phone: Your phone number (optional)
website: https://gustavoabr.eu

# Social links
twitter_username: GHAbreu
github_username:  ghabreu
instagram_username: gustavoabr.eu
linkedin_username: gustavo-abreu-44a73660

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I started working with telecommunications and built a career out of it. Earning certifications and climbing the ladder up to giving consultancy to large scale operations. But it wasn’t enough. This pursuit of knowledge and lack of fear from the unknown led me into bicycle touring Brazil. Where I did multiple volunteering jobs related to permaculture, bio-construction, and sustainability. Later I co-founded one of the firsts and few private, open to the public Makerspaces in Brazil. Which turns out to be a huge challenge, but still extremely rewarding.

  All of this brought me here to the Institute for Advanced Architecture of Catalonia, where I’m taking the Fab Academy course and proudly doing an internship at the Valldaura Self-sufficient Lab.
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Born in Belo Horizonte - Brazil. Since my childhood, I liked to tear toys apart to make new ones, understand how things work, ask a lot of why’s and learn something new every day.  Which made me pursue numerous courses and certifications such as Cisco CCNA, LPIC-1, Full Stack Development, and more. I'm also fluent in English, Portuguese, and Spanish.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-re  sume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
